// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBayfby274O-dw7OuG1zdOVP0hudnsjI3c',
    appId: '1:652416442474:web:51a196f13aa34ac37c2a13',
    messagingSenderId: '652416442474',
    projectId: 'test-f1831',
    authDomain: 'test-f1831.firebaseapp.com',
    databaseURL: 'https://test-f1831.firebaseio.com',
    storageBucket: 'test-f1831.appspot.com',
    measurementId: 'G-64RF0EYFK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeuh38W4Wu-AMQuYSZiBZ0zASLoBMeLck',
    appId: '1:652416442474:android:72db4b983cda88ba7c2a13',
    messagingSenderId: '652416442474',
    projectId: 'test-f1831',
    databaseURL: 'https://test-f1831.firebaseio.com',
    storageBucket: 'test-f1831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7LtOF9CS1tPliwxrbOuCk5Fmx6Nsq6WE',
    appId: '1:652416442474:ios:cca3394b6d76ab747c2a13',
    messagingSenderId: '652416442474',
    projectId: 'test-f1831',
    databaseURL: 'https://test-f1831.firebaseio.com',
    storageBucket: 'test-f1831.appspot.com',
    iosClientId: '652416442474-7o2qmvunda92dh69i0ktvanj10pb7g4s.apps.googleusercontent.com',
    iosBundleId: 'com.proinators.jeeLibrary',
  );
}
